apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: evil-christoph
  title: A Manager # shown in the table
spec:
  profile:
    displayName: A Manager # shown on the detail page
    picture: https://avatars.githubusercontent.com/u/292031457?v=4
  memberOf: [team-c, managers]
