global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-tech-radar
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-acr
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-jfrog-artifactory
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-nexus-repository-manager
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-quay
        disabled: false

upstream:
  backstage:
    image:
      registry: registry.redhat.io
      repository: rhdh/rhdh-hub-rhel9@sha256
      tag: d2889b704e21cb0fbea9f0df4420ce3919b65c0ed93e2041947b0beb4b31f1fc
      pullPolicy: Always

    appConfig:
      app:
        baseUrl: 'https://{{- include "janus-idp.hostname" . }}'
        # https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/getting_started_with_red_hat_developer_hub/assembly-customize-rhdh-theme#proc-customize-rhdh-branding_assembly-customize-rhdh-theme
        branding:
          theme:
            light:
              palette:
                primary:
                  main: '#00ff00'
                navigation:
                  indicator: '#00ffff'
              pageTheme:
                default:
                  backgroundColor: ['#00ff00', '#0000ff']
            dark:
              palette:
                primary:
                  main: '#00ff00'
                navigation:
                  indicator: '#00ffff'
              pageTheme:
                default:
                  backgroundColor: ['#00ff00', '#0000ff']

      backend:
        baseUrl: 'https://{{- include "janus-idp.hostname" . }}'
        cors:
          origin: 'https://{{- include "janus-idp.hostname" . }}'
        database:
          connection:
            password: ${POSTGRESQL_ADMIN_PASSWORD}
            user: postgres
        auth:
          keys:
            - secret: ${BACKEND_SECRET}

      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]

      permission:
        enabled: true
        rbac:
          pluginsWithPermission:
            # - catalog
            # - scaffolder
            # - policy
            # - kubernetes
          admin:
            superUsers:
              - name: user:default/christoph-jerolimov

  # reduce memoty usage
  postgresql:
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
